Living_Faith/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('church.urls')),



]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

church/urls.py
from django.urls import path
from . import views

app_name = 'church'


urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('ay', views.upload, name='upload' ),
    path('cells', views.wsf, name='wsf_list'),
    path('books', views.shop, name='book_list'),
    path('media', views.studio, name='nice'),
    path('halelluyah', views.tropics, name='wonder'),
    #path('myday', views.ict,  name='videos'),
    #path('faith', views.prog,  name='event'),
    path('congrat', views.topics, name='topics'),
    path('mercy(?P<topic_id>\d+)$', views.topic, name='good'),
    path('miracles(?P<tropic_id>\d+)$', views.tropic, name='no'),
    path('yaf', views.Yaf, name='amen'),
    path('wow', views.contact, name='back'),
     path('woow', views.yafcontact, name='alayo'),
    path('new', views.tops, name='new'),
    path('(?P<top_id>\d+)$', views.top, name='news')
]

church/models.py
from django.db import models
from django.forms import ModelForm, Textarea, TextInput


class Video(models.Model):
    name = models.CharField(max_length=555)
    videofile = models.FileField(upload_to='Videos/', null=True,)

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=222)
    author = models.CharField(max_length=222)
    pdf = models.FileField(upload_to='Books/Month/')


    class Meta:
        verbose_name_plural = "WSF"


    def __str__(self):
        return self.title







class Bookshop(models.Model):
    title = models.CharField(max_length=222)
    author = models.CharField(max_length=222)
    pdf = models.FileField(upload_to='Books/Month/')


    def __str__(self):
        return self.title


class Topic(models.Model):
    text = models.CharField(max_length=1000)
    date_added = models.DateTimeField(auto_now_add=True)


    class Meta:
        verbose_name_plural = 'LIVING FAITH PASTORATE HEADLINES'


    def __str__(self):
        return self.text


class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'LIVING FAITH PASTORATE'

        def __str__(self):
            return self.text[:50] + "..."


class Tropic(models.Model):
    text = models.CharField(max_length=1000)
    date_added = models.DateTimeField(auto_now_add=True)


    class Meta:
        verbose_name_plural = 'TESTIMONY HEADLINE'

    def __str__(self):
        return self.text


class Dentry(models.Model):
    tropic = models.ForeignKey(Tropic, on_delete=models.CASCADE)
    text = models.TextField()
    testifier = models.CharField(max_length=234)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'TESTIMONY'

        def __str__(self):
            return self.text[:50] + "..."


class Contact(models.Model):
    email = models.EmailField()
    subject = models.CharField(max_length=200)
    message = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email



class YafContact(models.Model):
    STATUS = (
        (1, 'New'),
        (2, 'Read'),
    )
    name = models.CharField(max_length=222)
    email = models.EmailField()
    subject = models.CharField(max_length=200)
    message = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS,default=1)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = 'Youth Alive Contact'
        verbose_name_plural = 'Youth Alive Contacts'


class YafContactForm(ModelForm):
    class Meta:
        model = YafContact
        fields = ['name', 'email', 'subject', 'message']
        widgets = {
            'name' : TextInput(attrs={'class': 'input', 'placeholder': 'Name & Surname....'}),
            'subject' : TextInput(attrs={'class': 'input', 'placeholder': 'Your HeadLine......'}),
            'email' : TextInput(attrs={'class': 'input', 'placeholder': 'realbuar@gmail.com'}),
            'message': Textarea(attrs={'class': 'input', 'placeholder': 'Your Message........'}),
        }






class Now(models.Model):
    gallery = models.FileField(upload_to='photo/%Y/%m/%d', blank=True)
    date_added = models.DateTimeField(auto_now_add=True)
    topic = models.CharField(max_length=234)

    def __str__(self):
        return self.topic


class New(models.Model):
    top = models.ForeignKey(Now, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text[:50] + "..."


class One(models.Model):
    name = models.CharField(max_length=333)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

church/forms.py
from django import forms
from .models import Book, Topic,  Tropic,  Contact, YafContact



class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ('title', 'author', 'pdf')



class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class TropicForm(forms.ModelForm):
    class Meta:
        model = Tropic
        fields = ['text']
        labels = {'text': ''}


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = "__all__"

class YafContactForm(forms.ModelForm):
    class Meta:
        model = YafContact
        fields = "__all__"

church/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.views.generic import TemplateView
from django.core.files.storage import FileSystemStorage
from .forms import BookForm, ContactForm, YafContactForm
from .models import Book, Video, Topic, Tropic,Dentry, Bookshop, Contact, Now, YafContact

from django.contrib import messages


class Home(TemplateView):
    template_name = 'church/home.html'


"""
def upload(request):
    context = {}
    if request.method == 'POST':
        uploaded_file = request.FILES['document']
        fs = FileSystemStorage()
        name = fs.save(uploaded_file.name, uploaded_file)
        context['url'] = url = fs.url(name)
    return render(request, 'church/upload.html', context)

"""

def upload(request):
    videos = Video.objects.all()
    return render(request, 'church/upload.html', {
        'videos': videos
    })





def wsf(request):
    books = Book.objects.all()
    return render(request,'church/wsf_list.html', {
        'books': books
    })

"""
def book_month(request):
    if request.method == 'POST':
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('church:wsf_list')
    else:
        form = BookForm()
    return render(request,'church/book_list.html', {
        'form': form
    })

"""


def shop(request):
    bookshops = Bookshop.objects.all()
    return render(request,'church/book_list.html', {
        'bookshops': bookshops
    })



def contact(request):
    if request.method == 'POST':
        email_d = request.POST.get('email')
        subject_e = request.POST.get('subject')
        message_f = request.POST.get('message')

        a = Contact(email=email_d, subject=subject_e, message=message_f)
        a.save()
        return redirect(request, 'church/back.html', {})
    else:
        return render(request, 'church/back.html')



def yafcontact(request):
    if request.method == 'POST':
        email_a = request.POST.get('email')
        name_b = request.POST.get('name')
        subject_c = request.POST.get('subject')
        message_d = request.POST.get('message')

        d = YafContact(email=email_a, name=name_b, subject=subject_c, message=message_d)
        d.save()
        return render(request, 'church/alayo.html', {})
    else:
        return render(request, 'church/alayo.html')








def studio(request):
    return render(request, 'church/nice.html')

"""
def ict(request):
    return render(request, 'church/upload.html')

"""



def topics(request):
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'church/topics.html', context)


def topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'church/good.html', context)




def tropics(request):
    tropics = Tropic.objects.order_by('date_added')
    context = {'tropics': tropics}
    return render(request, 'church/wonder.html', context)


def tropic(request, tropic_id):
    tropic = Tropic.objects.get(id=tropic_id)
    dentries = tropic.dentry_set.order_by('-date_added')
    context = {'tropic': tropic, 'dentries': dentries}
    return render(request, 'church/no.html', context)


def Yaf(request):
    return render(request, 'church/amen.html')







def tops(request):
    tops = Now.objects.order_by('date_added')
    context = {'tops':tops}
    return render(request, 'church/new.html', context)


def top(request, top_id):
    top = Now.objects.get(id=top_id)
    news = top.new_set.order_by('-date_added')
    context = {'top':top, 'news':news}
    return render(request, 'church/news.html', context)

church/templates/church/alayo.html
{% extends "church/base_yaf.html" %}
{% load static %}
{% block content %}
<br>
<br>
<br>
<br>
<br>

<br>
<br>
<br>



<div class="footer footer-content">
    <div class="container">
        <div class="row">
            <div class="col-sm-6 mx-auto" style="margin-top: 70px">
                <form action="{% url 'church:alayo' %}" method="POST">
                    {% csrf_token %}
                    <div class="form-group row">
                        <label class="col-2 col-form-label">Name</label>
                        <div class="col-10">
                            <input type="text" name="name" class="form-control " placeholder="Your Surname First...">
                        </div>

                    </div>
                    <div class="form-group row">
                        <label class="col-2 col-form-label">Email</label>
                        <div class="col-10">
                            <input type="email" name="email" class="form-control " placeholder="Your email address...">
                        </div>

                    </div>
                    <div class="form-group row">
                        <label class="col-2 col-form-label">Subject</label>
                        <div class="col-10">
                            <input name="subject" class="form-control" type="text" placeholder="Your Subject ...">
                        </div>

                    </div>
                    <div class="form-group row">
                        <label class="col-2 col-form-label">Message</label>
                        <div class="col-10">
                            <textarea name="message" class="form-control" cols="30" rows="6" placeholder="Your Message...."></textarea>
                        </div>

                    </div>
                    <div class="pull-right">
                        <button type="submit" class="btn btn-big contact-btn float-right">
                            <i class="fas fa-envelope"></i>
                                Send
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


<br>
<br>
<br>
<br>
<br>

<br>
<br>
<br>
{% include 'church/yaf_footer.html' %}

{% endblock content %}

<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

church/templates/church/amen.html
{% extends "church/base_yaf.html" %}
{% load static %}
{% block content %}
    <title>studio</title>

<body>
<img src="static/img/bishop.jpg" alt="JESUS IS MY SAVIOUR" width="550" height="350" align="centre" /><img src="static/img/pastor.jpg" alt="JESUS IS MY SAVIOUR" width="350" height="350" align="centre" />

<h5 style="color:red"> WELCOME  to  YOUTH ALIVE FELLOWSHIP </h5>
<h5 style="color:blue">THE GIANT IN YOU IS COMING ALIVE THIS YEAR</h5><h5 style="color:green"> STAY CONNECTED THIS IS YOUR TIME</h5>
<h5 style="color:red">to ENCOUNTER LIBERATION </h5>
><img src="static/img/nice.jpg" alt="JESUS IS MY SAVIOUR" width="900" height="650" align="centre" />




</body>
<br>
<br>
<br>
<br>
<br>

<br>
<br>
<br>

{% include 'church/yaf_footer.html' %}

</html>


{% endblock content %}

<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

church/templates/church/back.html
{% extends 'church/base.html' %}
{% load static %}
{% block content %}
<br>
<br>
<br>
<br>
<br>

<br>
<br>
<br>



<div class="footer footer-content">
    <div class="container">
        <div class="row">
            <div class="col-sm-6 mx-auto" style="margin-top: 70px">
                <form action="{% url 'church:back' %}" method="POST">
                    {% csrf_token %}
                    <div class="form-group row">
                        <label class="col-2 col-form-label">Email</label>
                        <div class="col-10">
                            <input type="email" name="email" class="form-control " placeholder="Your email address...">
                        </div>

                    </div>
                    <div class="form-group row">
                        <label class="col-2 col-form-label">Subject</label>
                        <div class="col-10">
                            <input name="subject" class="form-control" type="text" placeholder="Your Subject ...">
                        </div>

                    </div>
                    <div class="form-group row">
                        <label class="col-2 col-form-label">Message</label>
                        <div class="col-10">
                            <textarea name="message" class="form-control" cols="30" rows="6" placeholder="Your Message...."></textarea>
                        </div>

                    </div>
                    <div class="pull-right">
                        <button type="submit" class="btn btn-big contact-btn float-right">
                            <i class="fas fa-envelope"></i>
                                Send
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<br>
<br>
<br>
<br>
<br>

<br>
<br>
<br>



{% include 'church/footer.html' %}

{% endblock content %}

<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

church/templates/church/base_yaf.html
<img src="static/img/winners.png" alt="JESUS IS MY SAVIOUR" width="200" height="120"  align="centre" />

{% load static %}
<!DOCTYPE html>
<html  lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title %}Winners' Chapel Total Garden{% endblock %}</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Peralta" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/winners.css' %}">
</head>
<body>


            <div class="classy-navbar-toggler">
              <span class="navbarToggler"><span></span><span></span><span></span></span>
            </div>

   
            <div class="classy-menu">


              <div class="classycloseIcon">
                <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
              </div>






<div id="side-menu">
    <ul class="bhuwah">
        <li><a href="{% url 'church:home' %}">HOME</a></li>
        <li><a href="{% url  'church:topics' %}">LIVING FAITH </a></li>
        <li> <a href="{% url  'church:amen' %}" > YOUTH ALIVE </a></li>
        <li><a href="{% url  'church:nice' %}">MEDIA HOUSE</a>
           <ul>
              <li><a href="{% url  'church:wonder' %}"> TESTIMONIES </a></li>
              <li><a href="{% url  'church:upload' %}"> PROPHETIC DECLEARATION</a></li>
           </ul>

    </ul>




</div >






    <div class="container">
        <div class="page-header">






    {% block header %}{% endblock header %}


{% block content %}{% endblock content %}



        <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
        <script src="{% static 'js/popper.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
    </body>
</html>

church/templates/church/book_list.html
{% extends 'church/base.html' %}
{% load static %}
{% block content %}
<br>
<br>
<br>


    <h1>I AM THE HOME CELL </h1>
    <table class="table">
      <thead>
        <tr>
            <th>Title</th>
            <th>Author</th>
            <th>Download</th>
        </tr>
      </thead>
      <tbody>
        {% for book in books %}
            <tr>
                <td>{{ book.title }}</td>
                <td>{{ book.author }}</td>
                <td>
                    <a href="{{ book.pdf.url }}" class="btn btn-primary" target="_blank">
                        DOWNLOAD BOOK
                    </a>
                </td>
            </tr>
        {% endfor %}
      </tbody>
    </table>

{% endblock %}
<br>
<br>
<br>
<br>
<br>

<br>
<br>
<br>


{% include 'church/footer.html' %}

church/templates/church/event.html
{% extends "church/base.html" %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<br>
<br>
<br>
<h5 style="color:blue">GOD IS A GREAT GOD <br>HE IS WORKING WONDERS IN OUR MIGHT</h5>
<br>

<img src="static/img/RP.png" alt="JESUS IS MY SAVIOUR" width="1100" height="500"  align="centre" >

</body>



</body>
<br>
<br>
<br>
<br>
<br>

<br>
<br>
<br>
{% include 'church/footer.html' %}
</html>
{% endblock content %}

<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

church/templates/church/footer.html
{% load static %}



    <div class="footer">
		<div class="footer-content">
			<div class="footer-section about">
                <h1 class="logo-text"><span>Winners </span>Chapel</h1>
                
                <p>
                    "And i will restore to you the years that the
                    locust hath eaten, the cankerworm, the
                    caterpillar,and the palmerworm, my great army
                    which i sent among you"
                    Joel 2:25
                </p>
                <div>
                    <span><i class="fas fa-phone"></i>&nbsp; +234-803-578-4536</span>
                    <p><span><i class="fas fa-envelope"></i>&nbsp; info@winnerschapeltotalgarden.org</span></p>
                </div>
                <div class="socials">
                    <a href="https://www.facebook.com/realbuar"><i class="fab fa-facebook"></i> </a>
                    <a href="https://www.instagram.com/realbuar"><i class="fab fa-instagram"></i> </a>
                    <a href="https://twitter.com/realbuar"><i class="fab fa-twitter"></i> </a>
                    <a href="https://www.youtube.com/realbuar"><i class="fab fa-youtube"></i> </a>
                </div>
            </div>
			<div class="footer-section links">
                <h2>Quick Links</h2>
            <br>

                <a href="{% url 'church:wsf_list' %}">
                    W.S.F
                </a>

                <a href="{% url 'church:book_list' %}">
                    Books of the Month
                </a>
                <a href="{% url 'church:new' %}">
                    News
                </a>
                <a href="{% url 'church:back' %}">
                    Contact Us
                </a>
                <a href="{% url  'church:amen' %}" >
                    Youth Alive Fellowship
                </a>

            </div>


			<div class="footer-section contact-form">
                <h2>Services Times </h2>
                <br>
                <p>Sunday: 7AM, 9.30AM</p>
                <p>Wednesday: 5PM</p>
                <p>Covenant Hour of Prayer:</p>
                <p>Mon to Fri: 6AM - 7AM</p>
                <p><img src="static/img/blessed.png"></p>
               

            </div>

		</div>
        <div class="footer-bottom">
            <p>
                    Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This  is  with <i class="fa fa-heart-o" aria-hidden="true"></i> <i class="fa fa-heart" aria-hidden="true"></i>
            </p>
        </div>
	</div>

church/templates/church/home.html
{% extends "church/base.html" %}
{% load static %}
{% block content %}

<body>
<br/>
<br/>
<br/>


                                                <br><h1 style="color: blue" > WELCOME TO<br/> WINNERS CHAPEL TOTAL GARDEN</h1><br/>

<img src="static/img/RP.png" alt="JESUS IS MY SAVIOUR" width="1100" height="500"  align="centre" >
<img src="static/img/niw.jpg" alt="JESUS IS MY SAVIOUR" width="550" height="450"  align="centre"><img src="static/img/technical.jpg"  width="550" height="450"  align="centre">
                                                    <p style="color: purple"><b>HERE IS MEANT FOR PEOPLE THAT ARE READY TO WIN</b>
                                                        <br/><b style="color:black">ALL  BATTLES OF LIFE <br/></b>
                                                        <h5 style="color:blue">THROUGH</h5>
                                                        <h4 style="color: red">HEARING, <br/> READING  AND FOLLOWING </h4>
                                                        <h3 style="color: yellow">THE LIBERATION MANDATE</h3> <br/>
                                                        <h2 style="color: green"> HALELUYAH !!!.</h2>
                                                    </p>

</body>
<br>
<br>
<br>
<br>
<br>

<br>
<br>
<br>
{% include 'church/footer.html' %}



{% endblock content %}

<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

church/templates/church/new.html
{% extends 'church/base.html' %}
{% load static %}
{% block content %}


<br>

<br>

<br>

        <ul>
            {% for top in tops %}
                <h5>
                    <a href="{% url 'news' top.id %}">{{ top }}</a>
                </h5>
            {% endfor %}
        </ul>


<br>
<br>
<br>
<br>
<br>

<br>
<br>
<br>
{% include 'church/footer.html' %}


{% endblock content %}

<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

church/templates/church/nice.html
{% extends "church/base.html" %}
{% load static %}
{% block content %}
    <title>studio</title>

<body>
    <div>
                <br>
                <br>
                <br>
                <br>
                <br>

            <h2 id="ade" > WELCOME  to  MEDIA </h2>

            <img src="static/img/2.jpg" alt="JESUS IS MY SAVIOUR" width="550" height="350"  align="centre" />
            <img src="static/img/5.jpg" alt="JESUS IS MY SAVIOUR" width="550" height="350" align="centre" />
            <br>
        <br>
            <h1 style="COLOR:BLUE">WE ARE CELEBRATING AND PRODUCING IN CHRIST </h1>
        <h2 id="ade">JESUS</h2>
        <br>
            <img src="static/img/3.jpg" alt="JESUS IS MY SAVIOUR" width="350" height="350"  align="centre" />
            <img src="static/img/4.jpg" alt="JESUS IS MY SAVIOUR" width="350" height="350"  align="centre" />
            <img src="static/img/1.jpg" alt="JESUS IS MY SAVIOUR" width="350" height="350" align="centre" />

    </div>




</body>

<br>
<br>
<br>
<br>
<br>

<br>
<br>
<br>
{% include 'church/footer.html' %}


</html>


{% endblock content %}

<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

church/templates/church/no.html
{% extends 'church/base.html' %}
{% load static %}
{% block content %}



<br>

<br>

<br>
<br>
<br>
<br>

<a href="{% url  'church:wonder' %}"><button>Back</button></a>
<br>
<br>
<br>
     <h5 style="color:red">{{ tropic }}</h5>

    <ul>
       {% for dentry in dentries %}
          <li>
            <h5 style="color:red">{{ dentry.date_added|date:'M d, Y H:1'}}</h5>
            <p style="color:green">{{ dentry.text|linebreaks }}</p>
            <h3 style="color:blue">{{ dentry.testifier }}</h3>
          </li>
       {% endfor %}
    </ul>



<br>
<br>
<br>
<br>
<br>

<br>
<br>
<br>




{% endblock content %}

church/templates/church/topics.html
{% extends 'church/base.html' %}
{% load static %}
{% block content %}


<br>

<br>

<br>

    <ul>
       {% for topic in topics %}
          <p>
              <a href="{% url 'church:good' topic.id %}" class="btn btn-info" target="_blank">
                  {{ topic }}
              </a>
          </p>
       {% endfor %}
    </ul>
<br>

<br>

<br>
<br>

<br>

<br>

{% include 'church/footer.html' %}
{% endblock content %}

<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

church/templates/church/upload.html
{% extends "church/base.html" %}
{% load static %}
{% block content %}
<br>
<br>
<br>
<br>
<br>

<br>
<br>
<br>




        <table class="table">
          <thead>
            <tr>
                <th><h1>VIDEOS</h1></th>
            </tr>
          </thead>
          <tbody>
            {% for video in videos %}

                <tr>
                    <td>
                       <a href="{{ video.videofile.url }}" class="btn btn-primary" target="_blank">
                            <h2>{{ video.name }}</h2>
                          </a>

                    </td>
                </tr>
            {% endfor %}
          </tbody>
        </table>

<br>
<br>
<br>
<br>
<br>

<br>
<br>
<br>
{% include 'church/footer.html' %}

{% endblock content %}

<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

church/templates/church/wsf_list.html
{% extends "church/base_yaf.html" %}
{% load static %}
{% block content %}

<br>
<br>
<br>


    <h1>I AM THE HOME CELL </h1>
    <table class="table">
      <thead>
        <tr>
            <th>Title</th>
            <th>Author</th>
            <th>Download</th>
        </tr>
      </thead>
      <tbody>
        {% for book in books %}
            <tr>
                <td>{{ book.title }}</td>
                <td>{{ book.author }}</td>
                <td>
                    <a href="{{ book.pdf.url }}" class="btn btn-primary" target="_blank">
                        DOWNLOAD BOOK
                    </a>
                </td>
            </tr>
        {% endfor %}
      </tbody>
    </table>


<br>
<br>
<br>
<br>
<br>

<br>
<br>
<br>
{% include 'church/footer.html' %}



{% endblock content %}